# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
gmaps.configure(api_key="")#given when submitting HW in BCS


# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cities_df = pd.read_csv("output_data/cities.csv")
cities_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,mountain home,20,US,1587007989,38,43.13,-115.69,48.20,17.22
1,1,kurilsk,100,RU,1587007989,93,45.23,147.88,30.34,15.50
2,2,khatanga,22,RU,1587007989,91,71.97,102.50,3.36,8.08
3,3,dwarka,40,IN,1587007989,78,22.24,68.97,80.06,17.31
4,4,esperance,90,AU,1587007990,67,-33.87,121.90,62.60,6.93

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
humidity=cities_df["Humidity"]
maxhumidity=humidity.max()
locations=cities_df[["Lat","Lng"]]

In [4]:
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,dissipating=False, max_intensity=maxhumidity,point_radius=3)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
new_df=cities_df.loc[(cities_df["Max Temp"] > 70) & (cities_df["Max Temp"] < 80) & (cities_df["Cloudiness"] == 0), :]
new_df = new_df.dropna()
new_df.reset_index(inplace=True)

del new_df["index"]
new_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,50,pisco,0,PE,1587007995,73,-13.70,-76.22,73.40,3.36
1,94,ati,0,TD,1587008000,15,13.22,18.34,74.34,12.01
2,271,mana,0,GF,1587008022,83,5.66,-53.78,75.94,6.06
3,437,maine-soroa,0,NE,1587008039,17,13.21,12.02,76.57,10.60
4,473,ganzhou,0,CN,1587008044,49,28.82,115.43,77.22,10.04

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [14]:
hotellist = []
for i in range(len(new_df)):
    lat = new_df.loc[i,'Lat']
    lng = new_df.loc[i,'Lng']

    params = {
        "location": f"{lat},{lng}",
        "radius": 5000,
        "types" : "hotel",
        "key": "AIzaSyC87a1RJnSup6AAwmsP-Ai2bstAvJT-FsI"
    }
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params)
    response_json = response.json()
    #pprint(response_json)
    try:
        hotellist.append(response_json['results'][0]['name'])
    except:
        hotellist.append("")
new_df["Hotel Name"] = hotellist
new_df = new_df.dropna()
new_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
0,50,pisco,0,PE,1587007995,73,-13.70,-76.22,73.40,3.36,Pisco
1,94,ati,0,TD,1587008000,15,13.22,18.34,74.34,12.01,Ati
2,271,mana,0,GF,1587008022,83,5.66,-53.78,75.94,6.06,Mana
3,437,maine-soroa,0,NE,1587008039,17,13.21,12.02,76.57,10.60,Maïné-Soroa
4,473,ganzhou,0,CN,1587008044,49,28.82,115.43,77.22,10.04,Nanchang

In [ ]:

# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [7]:
# Add marker layer ontop of heat map

markers=gmaps.marker_layer(locations)
fig.add_layer(markers)
# Display Map
fig

Figure(layout=FigureLayout(height='420px'))